### ISSUE TITLE
reduce the size of vendor.js 

### ISSUE THREAD

**Issue by nzomkxia** [apache/dubbo-admin#248]

**Comment by htynkn** [comment]
disable devtool can reduce from 16M to 6M, but it still too big

**Comment by htynkn** [comment]
+ spilt vendor file to two file
1.  brace related (it's using by AceEditor). this one is too big, need investigate more
2. others, include vue and etc..

+ upgrade webpack from 3 to 4
1.use vue-cli instead of custom config webpack
2.upgrade dev dependencies doesn't help reducing file size

+ enable spring boot gzip
network size from 6mb to 1.6mb

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
